### ISSUE TITLE
C file IndexError: list index out of range in the method 'out_to_items' 

### ISSUE THREAD

**Issue by lianghu** [rampage644/sublime-rtags#28]
Hi Sergei,

I met a different IndexError than #20.
Is it because the code base is large?

Here is the trace back:

/usr/local/bin/rc --silent-query --absolute-path -f /home/lianghu/openwrt/marvell/uboot/drivers/power/freq.c:228:27
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 568, in run_
    return self.run(edit, **args)
  File "/home/lianghu/.config/sublime-text-3/Packages/sublime-rtags/rtags.py", line 145, in run
    self._action(out, err)
  File "/home/lianghu/.config/sublime-text-3/Packages/sublime-rtags/rtags.py", line 182, in _action
    items = list(map(out_to_items, items))
  File "/home/lianghu/.config/sublime-text-3/Packages/sublime-rtags/rtags.py", line 180, in out_to_items
    (file, line, _, usage) = re.findall(reg, item)[0]
IndexError: list index out of range

**Comment by lianghu** [comment]
@tillt

**Comment by lianghu** [comment]
it seems it only indexed one of the project in the workspace

**Comment by lianghu** [comment]
it's upstream rtags related issue

**Comment by tillt** [comment]
Yeah, it is a bit unfortunate that the result of such missing index is that nasty out of range error. I feel we should try to fix that as well and give the user some proper feedback.

**Comment by tillt** [comment]
See https://github.com/rampage644/sublime-rtags/pull/36
